version: '2'

services:

  database-postgres:
    build:
      context: ./marvel-database
      dockerfile: Dockerfile
    container_name: marvel-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marvel
      - POSTGRES_USER=admin
  sonar:
    image: sonarqube:latest
    ports:
      - "9000:9000"